# Generated by Django 2.0.2 on 2018-04-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180426_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('crse', models.TextField(blank=True, db_column='Crse', null=True)),
                ('courseoverall', models.FloatField(blank=True, db_column='CourseOverall', null=True)),
                ('hoursperwkinclclass', models.TextField(blank=True, db_column='HoursPerWkInclClass', null=True)),
                ('challenge', models.FloatField(blank=True, db_column='Challenge', null=True)),
                ('howmuchlearned', models.FloatField(blank=True, db_column='HowMuchLearned', null=True)),
                ('crstitle', models.TextField(blank=True, db_column='CrsTitle', null=True)),
                ('index', models.AutoField(db_column='index', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
    ]
