# Generated by Django 2.0.2 on 2018-04-26 10:18

from django.db import migrations
import django_mysql.models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coursePlan',
            field=django_mysql.models.JSONField(default=main.models.default_coursePlan),
        ),
    ]
